#from libraries.literals import GAME_LEVEL_FIRST

# Game levels
GAME_LEVEL_TITLE = 0
GAME_LEVEL_STORY = 1
GAME_LEVEL_BLUE_PLANET = 21
GAME_LEVEL_ADDITION_LEVEL1 = 22
GAME_LEVEL_ADDITION_LEVEL2 = 23
GAME_LEVEL_ADDITION_LEVEL3 = 24
GAME_LEVEL_ADDITION_BOSS = 29

GAME_LEVEL_RED_PLANET = 31
GAME_LEVEL_SUBSTRACTION_LEVEL1 = 32
GAME_LEVEL_SUBSTRACTION_LEVEL2 = 33
GAME_LEVEL_SUBSTRACTION_LEVEL3 = 34
GAME_LEVEL_SUBSTRACTION_BOSS = 39

GAME_LEVEL_GREEN_PLANET = 41
GAME_LEVEL_MULTIPLICATION_LEVEL1 = 42
GAME_LEVEL_MULTIPLICATION_LEVEL2 = 43
GAME_LEVEL_MULTIPLICATION_LEVEL3 = 44
GAME_LEVEL_MULTIPLICATION_BOSS = 49

GAME_LEVEL_SAND_PLANET = 51
GAME_LEVEL_DIVISION_LEVEL1 = 52
GAME_LEVEL_DIVISION_LEVEL2 = 53
GAME_LEVEL_DIVISION_LEVEL3 = 54
GAME_LEVEL_DIVISION_BOSS = 59

# Math operations
OPERATOR_ADD = 1
OPERATOR_SUB = 2
OPERATOR_MUL = 3
OPERATOR_DIV = 4

# Planet names
TEXT_PLANET_RED_NAME = 'FIRENIUS'
TEXT_PLANET_BLUE_NAME = 'WATERNIOUS'
TEXT_PLANET_YELLOW_NAME = 'YELLONIOUS'
TEXT_PLANET_GREEN_NAME = 'PLANTONIOUS'
TEXT_PLANET_SAND_NAME = 'DESERTNIOUS'
