import pygame

EVENT_STORY_SCRIPT_CAPTION = pygame.USEREVENT + 1
EVENT_STORY_SCRIPT_TYPE = pygame.USEREVENT + 7
EVENT_STORY_SCRIPT_DELAY_BEFORE_SHIP = pygame.USEREVENT + 2
EVENT_STORY_SCRIPT_DELAY_FOR_LAUGH = pygame.USEREVENT + 5
EVENT_STORY_SCRIPT_POST_LAUGH_DELAY = pygame.USEREVENT + 6
