DEFAULT_SCREENSIZE = [512, 448]

SEX_MALE = 'm'
SEX_FEMALE = 'f'

COLOR_BLACK = (0, 0, 0)
COLOR_ALMOST_BLACK = (1, 1, 1)
COLOR_WHITE = (255,255,255)
RESULT_BOX_SIZE = (54, 24)
RESULT_BOX_VERTICAL_OFFSET = 60

# Game strings
GAME_TITLE = 'Attack of the Moronians'
HEALTH_BAR_TEXT = 'Energy'
PAUSE_TEXT = 'PAUSE'
SCORE_TEXT = 'Score'
START_MESSAGE_TEXT = 'Press ENTER to start'
PAUSE_TEXT_VERTICAL_OFFSET = 100  # Vertical offset of the 'PAUSE' message
STORY_TEXT = 'Earth, year 2023'
GAME_OVER_TEXT = 'Game Over'
VERSION_TEXT = 'Version'
CREDITS_TEXT = '(c) 2013 Roberto Rosario'

# Game levels
GAME_LEVEL_TITLE = 0
GAME_LEVEL_STORY = 1
GAME_LEVEL_ADDITION_LEVEL = 2
GAME_LEVEL_SUBSTRACT_LEVEL = 3
GAME_LEVEL_MULTIPLICATION_LEVEL = 4
GAME_LEVEL_DIVISION_LEVEL = 5

